# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 01:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0003_dvd_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libuser',
            name='postalcode',
        ),
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.date(2016, 5, 24)),
        ),
    ]
