# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-20 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0006_auto_20160620_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
