# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-20 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0007_suggestion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
