# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import libapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0009_auto_20160624_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libitem',
            name='pubyr',
            field=models.IntegerField(validators=[libapp.models.clean_fields]),
        ),
    ]
